trigger:
  branches:
    include:
    - test

pool:
  name: jenkins  # Ensure this is your self-hosted agent pool name

steps:
  - checkout: self  # Default checkout of the repo into $(Build.SourcesDirectory)


  - script: |
      # Give permissions and run Playwright Python tests in /AzureRepo
      export PATH=$PATH:~/.local/bin
      pip install pytest pytest-playwright pytest-html
      playwright install
      sudo chown -R $(whoami):$(whoami) /var/lib/jenkins/myagent/_work/2/s/Test/Playwright
      pytest /var/lib/jenkins/myagent/_work/2/s/Test/Playwright/tests.py --html=/var/lib/jenkins/myagent/_work/2/s/Test/Playwright/reportPY.html
    displayName: 'Run Playwright Python tests'

  - script: |
      # Give permissions and run Playwright JS tests in /AzureRepo
      source ~/.bashrc
      cd /var/lib/jenkins/myagent/_work/2/s/Test/Playwright
      PLAYWRIGHT_JUNIT_OUTPUT_NAME=reportJS.xml npx playwright test --reporter=junit
    displayName: 'Run Playwright .JS tests'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '/var/lib/jenkins/myagent/_work/2/s/Test/Playwright/reportPY.html'
      ArtifactName: 'PythonTestReports'
      publishLocation: 'Container'
    displayName: 'Publish Python Test Report'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '/var/lib/jenkins/myagent/_work/2/s/Test/Playwright/reportJS.xml'
      ArtifactName: 'JavaScriptTestReports'
      publishLocation: 'Container'
    displayName: 'Publish JavaScript Test Report'
