trigger:
  branches:
    include:
      - main
pool:
  name: jenkins
steps:
  - checkout: self
  
  - script: >
      # Install dependencies
      pip install --user pytest pytest-playwright pytest-html
      playwright install
      export PATH=$PATH:/var/lib/jenkins/.local/bin/
    displayName: Install dependencies
  
  - script: >
      # Run Playwright Python tests in /AzureRepo
      sudo chown -R $(whoami):$(whoami) /var/lib/jenkins/myagent/_work/5/s/Test/Playwright
      python3 -m pytest /var/lib/jenkins/myagent/_work/5/s/Test/Playwright/tests.py
      --html=/var/lib/jenkins/myagent/_work/5/s/Test/Playwright/reportPY.html
    displayName: Run Playwright Python tests
  
  - script: >
      # Run Playwright JS tests in /AzureRepo
      cd /var/lib/jenkins/myagent/_work/5/s/Test/Playwright
      source ~/.bashrc
      npx playwright test
    displayName: Run Playwright .JS tests
  
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: /var/lib/jenkins/myagent/_work/5/s/Test/Playwright/reportPY.html
      ArtifactName: PythonTestReports
      publishLocation: Container
    displayName: Publish Python Test Report
  
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: /var/lib/jenkins/myagent/_work/5/s/playwright-report/index.html
      ArtifactName: JavaScriptTestReports
      publishLocation: Container
    displayName: Publish JavaScript Test Report
